# frozen_string_literal: true

# spec/support/pbt_rails.rb
#
# Two entry points and nothing else:
#
#   PbtRails.isolated { ... }   run a block inside a savepoint that is always rolled back
#   PbtRails.arb_for(Model)     a Pbt arbitrary of attribute hashes derived from schema + validations
#
# Deliberate refusals (each one is a place where a wrong guess would produce a
# green test that proves nothing):
#
#   - Never generates nil. "This column accepts nil" is a property you write, not a default.
#   - Ignores conditional validators (if:/unless:/on:). It cannot evaluate the condition.
#   - Refuses format: validators. A regex is a filter, not a generator; pass an override.
#   - Skips *_id columns. Foreign keys must point at rows that exist; pass an override
#     (PbtRails.arb_for(Comment, post_id: Pbt.constant(post.id))). This is a name heuristic:
#     a non-key column such as `external_id` is skipped too, and an override re-adds it.
#   - Skips column types it does not model (json, uuid, binary, arrays) when they are
#     nullable or defaulted, and raises when they are NOT NULL with no default.
#
# Overrides take any Pbt arbitrary, or a plain value (wrapped in Pbt.constant).
#
#   PbtRails.arb_for(Order, only: %i[total_cents currency], currency: Pbt.one_of("USD", "EUR"))
#
# Do not edit this file to make a property pass. Narrow the generator at the call site.

require "date"
require "bigdecimal"
require "pbt"

module PbtRails
  class Unsupported < StandardError; end

  # Fixed anchors: the same seed must reproduce the same values tomorrow.
  BASE_DATE = Date.new(2020, 1, 1)
  BASE_TIME = Time.utc(2020, 1, 1)
  DAY_RANGE = 3650              # +/- 10 years
  SECOND_RANGE = 315_360_000    # +/- 10 years
  INT_RANGE = 1_000_000         # wide enough to find sign and rounding bugs, narrow enough to stay legible
  STRING_MAX = 32
  FLOAT_UNIT = 100              # floats are generated as hundredths so they survive a round trip

  module_function

  # Applied at load time. `worker: :none` is not negotiable: Ractor workers cannot
  # call `expect`, cannot see `let`, and cannot share the ActiveRecord connection.
  def configure!
    Pbt.configure do |config|
      config.worker = :none
      config.num_runs = Integer(ENV["PBT_RUNS"]) if ENV["PBT_RUNS"]
      config.seed = Integer(ENV["PBT_SEED"]) if ENV["PBT_SEED"]
    end
  end

  # Runs the block in a savepoint and rolls it back, whatever happens.
  # Returns the block's value. Exceptions (including RSpec's ExpectationNotMetError,
  # which is not a StandardError) propagate so Pbt can shrink the failure.
  def isolated
    result = nil
    ActiveRecord::Base.transaction(requires_new: true) do
      result = yield
      raise ActiveRecord::Rollback
    end
    result
  end

  # @return [Pbt::Arbitrary::Arbitrary] arbitrary producing attribute hashes for `model`
  def arb_for(model, only: nil, except: [], **overrides)
    Pbt.fixed_hash(attribute_arbs(model, only: only, except: except, **overrides))
  end

  # @return [Hash{Symbol => Pbt::Arbitrary::Arbitrary}] one arbitrary per generated attribute
  def attribute_arbs(model, only: nil, except: [], **overrides)
    only = only&.map(&:to_sym)
    except = Array(except).map(&:to_sym)
    arbs = {}

    model.columns.each do |column|
      name = column.name.to_sym
      next if except.include?(name)
      next if only && !only.include?(name)
      next arbs[name] = to_arb(overrides[name]) if overrides.key?(name)
      next if structural?(model, column)

      arb = column_arb(model, column)
      arbs[name] = arb if arb
    end

    # Overrides may name virtual attributes and skipped columns alike.
    overrides.each do |name, value|
      next if except.include?(name)
      next if only && !only.include?(name)

      arbs[name] ||= to_arb(value)
    end

    raise Unsupported, "#{model} produced no generatable attributes; pass overrides" if arbs.empty?

    arbs
  end

  # Columns the model owns rather than the domain: keys, timestamps, STI, locking, foreign keys.
  def structural?(model, column)
    name = column.name
    return true if name == model.primary_key
    return true if %w[created_at updated_at].include?(name)
    return true if model.respond_to?(:inheritance_column) && name == model.inheritance_column
    return true if model.respond_to?(:locking_column) && name == model.locking_column
    return true if name.end_with?("_id")

    false
  end

  def column_arb(model, column)
    validators = applicable_validators(model, column.name)

    if validators.any? { |v| v.kind == :format }
      raise Unsupported, "#{model}##{column.name} has a format: validator. " \
        "Pass an override that generates matching values, or exclude the column."
    end

    values = enum_values(model, column.name) || inclusion_values(validators)
    return Pbt.one_of(*values) if values

    case column.type
    when :integer then integer_arb(validators)
    when :string, :text then string_arb(validators, column)
    when :boolean then Pbt.boolean
    when :decimal then decimal_arb(validators, column)
    when :float then float_arb(validators)
    when :date then Pbt.date(base_date: BASE_DATE, past_offset_days: -DAY_RANGE, future_offset_days: DAY_RANGE)
    when :datetime, :timestamp
      Pbt.time(base_time: BASE_TIME, past_offset_seconds: -SECOND_RANGE, future_offset_seconds: SECOND_RANGE)
    else
      return nil if column.null || !column.default.nil?

      raise Unsupported, "#{model}##{column.name} is #{column.type.inspect} and NOT NULL. Pass an override."
    end
  end

  def integer_arb(validators)
    min, max = integer_bounds(validators, -INT_RANGE, INT_RANGE)
    raise Unsupported, "numericality bounds leave no integers to generate" if min > max

    Pbt.integer(min: min, max: max)
  end

  def string_arb(validators, column)
    options = validators.find { |v| v.kind == :length }&.options || {}
    exact = options[:is]
    max = exact || [options[:maximum], column.limit, STRING_MAX].compact.min
    min = exact || options[:minimum] || (presence?(validators) ? 1 : 0)
    min = max if min > max

    # Alphanumeric on purpose: it survives every adapter's round trip, so an R1 failure
    # is a finding about the model, not about trailing whitespace or collation. Override
    # with Pbt.printable_ascii_string for anything you actually parse.
    Pbt.alphanumeric_string(min: min, max: max, empty: min.zero?)
  end

  def decimal_arb(validators, column)
    scale = column.scale || 2
    precision = column.precision || 12
    unit = 10**scale
    cap = [10**precision - 1, INT_RANGE * unit].min
    min, max = integer_bounds(validators, -cap, cap, unit: unit)
    raise Unsupported, "numericality bounds leave no decimals to generate" if min > max

    Pbt.integer(min: min, max: max).map(
      ->(units) { BigDecimal(units) / unit },
      ->(value) { (BigDecimal(value.to_s) * unit).to_i }
    )
  end

  def float_arb(validators)
    min, max = integer_bounds(validators, -INT_RANGE, INT_RANGE, unit: FLOAT_UNIT)
    raise Unsupported, "numericality bounds leave no floats to generate" if min > max

    Pbt.integer(min: min, max: max).map(
      ->(units) { units.fdiv(FLOAT_UNIT) },
      ->(value) { (value * FLOAT_UNIT).round }
    )
  end

  # Numericality options, expressed in whole units (1 for integers, 10**scale for decimals).
  def integer_bounds(validators, default_min, default_max, unit: 1)
    options = validators.select { |v| v.kind == :numericality }.map(&:options).reduce({}, :merge)
    min = default_min
    max = default_max

    if (range = options[:in])
      min = [min, scaled(range.first, unit)].max
      max = [max, range.exclude_end? ? scaled(range.last, unit) - 1 : scaled(range.last, unit)].min
    end
    min = [min, scaled(options[:greater_than_or_equal_to], unit)].max if options[:greater_than_or_equal_to]
    min = [min, scaled(options[:greater_than], unit) + 1].max if options[:greater_than]
    max = [max, scaled(options[:less_than_or_equal_to], unit)].min if options[:less_than_or_equal_to]
    max = [max, scaled(options[:less_than], unit) - 1].min if options[:less_than]
    min = max = scaled(options[:equal_to], unit) if options[:equal_to]

    [min, max]
  end

  def scaled(bound, unit)
    (BigDecimal(bound.to_s) * unit).to_i
  end

  def presence?(validators)
    validators.any? { |v| v.kind == :presence }
  end

  def applicable_validators(model, name)
    return [] unless model.respond_to?(:validators_on)

    model.validators_on(name).reject do |validator|
      options = validator.options
      options[:if] || options[:unless] || options[:on]
    end
  end

  def enum_values(model, name)
    return nil unless model.respond_to?(:defined_enums)

    model.defined_enums[name]&.keys
  end

  def inclusion_values(validators)
    options = validators.find { |v| v.kind == :inclusion }&.options
    return nil unless options

    values = options[:in] || options[:within]
    return nil unless values.respond_to?(:to_a)

    values.to_a
  end

  def to_arb(value)
    value.is_a?(Pbt::Arbitrary::Arbitrary) ? value : Pbt.constant(value)
  end
end

PbtRails.configure!
